### ISSUE TITLE
Chef exits with Fatal Error

### ISSUE THREAD

**Issue by syedrayees** [mconf/chef-recipes#4]
Chef Client failed. 8 resources updated
[2015-07-01T15:44:37+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

How to slove this problem???
Am installing Mconf-Live Standalone in a server running ubuntu 14.04 64bit

**Comment by fcecagno** [comment]
@syedrayees It's impossible to know why Chef exited unsuccessfully because you didn't attach a pastebin with the output of the command.
Anyway, in order to install latest Mconf-Live standalone, clone https://github.com/mconf-cookbooks/mconf-live-solo and run `install.sh`.

This repo is going to be deprecated soon and shouldn't be used any more.

**Comment by syedrayees** [comment]
After executing install.h 

W: Failed to fetch http://ppa.launchpad.net/libreoffice/libreoffice-4-0/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/libreoffice/libreoffice-4-0/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

Because of the above missing packages installation exited unsuccessfully 

Please tell me how to fix

**Comment by fcecagno** [comment]
It looks like a problem in your network, not a problem in the recipes. You can look into the code and try to execute the steps manually and figure out where the problem is. It's almost impossible to help you with so little information.
